# File: k8s/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dockersyrine12/backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_ACCESS_KEY
              value: "fakeMyKeyId"
            - name: AWS_SECRET_KEY
              value: "fakeSecretAccessKey"
            - name: DYNAMODB_TABLE
              value: "Users"
            - name: DYNAMODB_ENDPOINT
              value: "http://dynamodb:8000"
            - name: IS_LOCAL
              value: "true"
            - name: PORT
              value: "4000"
          volumeMounts:
            - name: uploads-volume
              mountPath: /app/uploads
            - name: files-volume
              mountPath: /app/files
      volumes:
        - name: uploads-volume
          emptyDir: {}
        - name: files-volume
          emptyDir: {}
