apiVersion: v1
kind: PersistentVolume
metadata:
  name: dynamodb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/dynamodb-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi