# File: k8s/dynamodb-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dynamodb
  labels:
    app: dynamodb
spec:
  selector:
    app: dynamodb
  ports:
    - protocol: TCP
      port: 8000       # ClusterIP port
      targetPort: 8000 # Pod’s containerPort
  type: ClusterIP     # Default; reachable by other pods at "dynamodb:8000"
